# Generated by Django 4.1.13 on 2026-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CGPA (Cumulative Grade Point Average)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, help_text='College/University name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='leetcode_link',
            field=models.URLField(blank=True, help_text='LeetCode profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
