# Generated by Django 4.1.13 on 2026-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cgpa_user_college_user_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch or specialization', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='codechef_link',
            field=models.URLField(blank=True, help_text='CodeChef profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='codeforces_link',
            field=models.URLField(blank=True, help_text='Codeforces profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, help_text='Course name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, help_text='Gender', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gfg_link',
            field=models.URLField(blank=True, help_text='GeeksforGeeks profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='hackerrank_link',
            field=models.URLField(blank=True, help_text='HackerRank profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, help_text='Year of study', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address (used as username)', max_length=254, unique=True),
        ),
    ]
