# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_branch_user_codechef_link_user_codeforces_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="github_link",
            field=models.URLField(blank=True, help_text="GitHub profile URL", null=True),
        ),
    ]
