# Generated by Django 4.1.13 on 2026-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_branch_user_codechef_link_user_codeforces_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_stats',
            field=models.JSONField(blank=True, help_text='Cached GitHub analysis data', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Last time coding platforms were analyzed', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leetcode_stats',
            field=models.JSONField(blank=True, help_text='Cached LeetCode analysis data', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_stats',
            field=models.JSONField(blank=True, help_text='Cached LinkedIn analysis data', null=True),
        ),
    ]
