# Generated by Django 4.1.13 on 2026-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_github_stats_user_last_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_about',
            field=models.TextField(blank=True, help_text='LinkedIn about summary'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_cert_count',
            field=models.IntegerField(blank=True, help_text='LinkedIn certifications count', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_experience_count',
            field=models.IntegerField(blank=True, help_text='LinkedIn experience count', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_headline',
            field=models.CharField(blank=True, help_text='LinkedIn headline', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_skill_count',
            field=models.IntegerField(blank=True, help_text='LinkedIn skills count', null=True),
        ),
    ]
