# Generated by Django 4.1.13 on 2026-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_linkedin_about_user_linkedin_cert_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_verified',
            field=models.BooleanField(default=False, help_text='Profile verified after AI interview completion'),
        ),
    ]
