# Generated by Codex on 2026-01-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_github_link_null"),
        ("accounts", "0006_user_profile_verified"),
    ]

    operations = []
