# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_0004_alter_user_github_link_null_0006_user_profile_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="leetcode_link",
            field=models.URLField(blank=True, help_text="LeetCode profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin_link",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="codechef_link",
            field=models.URLField(blank=True, help_text="CodeChef profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="hackerrank_link",
            field=models.URLField(blank=True, help_text="HackerRank profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="codeforces_link",
            field=models.URLField(blank=True, help_text="Codeforces profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gfg_link",
            field=models.URLField(blank=True, help_text="GeeksforGeeks profile URL", null=True),
        ),
    ]
