# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_optional_links_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, help_text="Full name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, help_text="Gender", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, help_text="Phone number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="course",
            field=models.CharField(blank=True, help_text="Course name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="branch",
            field=models.CharField(blank=True, help_text="Branch or specialization", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="year_of_study",
            field=models.CharField(blank=True, help_text="Year of study", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_skills",
            field=models.TextField(blank=True, help_text="Comma-separated list of skills", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin_headline",
            field=models.CharField(blank=True, help_text="LinkedIn headline", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin_about",
            field=models.TextField(blank=True, help_text="LinkedIn about summary", null=True),
        ),
    ]
