# Generated by Django 4.2 on 2026-03-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_optional_text_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval or rejection', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', help_text='Approval workflow state for privileged accounts', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the account was approved', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Company or institution name for recruiter/university accounts', max_length=255, null=True),
        ),
    ]
