from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard_view, name='skills-dashboard'),
    path('activities/', views.activities_view, name='skills-activities'),
    path('verification-steps/', views.verification_steps_view, name='skills-verification-steps'),
    path('recommendations/', views.recommendations_view, name='skills-recommendations'),
    path('skill-suggestions/', views.skill_suggestions_view, name='skills-suggestions'),
    path('skill-passport/', views.skill_passport_view, name='skills-passport'),
    path('skill-passport/pdf/', views.skill_passport_pdf_view, name='skills-passport-pdf'),
    path('resume/', views.resume_document_view, name='skills-resume'),
    path('resume-builder/', views.resume_builder_view, name='skills-resume-builder'),
    path('resume-builder/pdf/', views.resume_builder_pdf_view, name='skills-resume-builder-pdf'),
    path('notifications/', views.notifications_view, name='skills-notifications'),
    path('notifications/<int:notification_id>/read/', views.notification_read_view, name='skills-notification-read'),
    path('interview-schedules/', views.interview_schedules_view, name='skills-interview-schedules'),
    path('ai-interview/', views.ai_interview_view, name='skills-ai-interview'),
    path('ai-interview/action/', views.ai_interview_action_view, name='skills-ai-interview-action'),
    path('ai-generated-repos/', views.ai_generated_repos_view, name='skills-ai-generated-repos'),
    path('recruiter-dashboard/', views.recruiter_dashboard_view, name='recruiter-dashboard'),
    path('recruiter-dashboard/jobs/', views.recruiter_jobs_view, name='recruiter-jobs'),
    path('recruiter-dashboard/pipeline/<int:candidate_id>/', views.recruiter_pipeline_view, name='recruiter-pipeline'),
    path('recruiter-dashboard/saved-searches/', views.recruiter_saved_searches_view, name='recruiter-saved-searches'),
    path('recruiter-dashboard/report/<int:student_id>/', views.recruiter_candidate_report_view, name='recruiter-candidate-report'),
    path('recruiter-dashboard/resume/<int:student_id>/', views.recruiter_candidate_resume_view, name='recruiter-candidate-resume'),
    path('university-dashboard/', views.university_dashboard_view, name='university-dashboard'),
    path('university-dashboard/batch-upload/', views.university_batch_upload_view, name='university-batch-upload'),
    path('university-dashboard/interventions/<int:student_id>/', views.university_intervention_view, name='university-intervention'),
    path('university-dashboard/drives/', views.university_placement_drives_view, name='university-placement-drives'),
    path('code-analysis/', views.code_analysis_view, name='skills-code-analysis'),
    path('code-analysis/<int:report_id>/file/', views.code_analysis_file_view, name='skills-code-analysis-file'),
    path('media/', views.media_view, name='skills-media'),
    path('progress/', views.progress_view, name='skills-progress'),
    path('roadmap/', views.roadmap_view, name='skills-roadmap'),
    path('settings/', views.settings_view, name='skills-settings'),
    path('performance/', views.performance_view, name='skills-performance'),
]
