# Generated by Django 4.1.13 on 2026-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='score_type',
            field=models.CharField(choices=[('coding_skill_index', 'Coding Skill Index'), ('communication_score', 'Communication Score'), ('authenticity_score', 'Authenticity Score'), ('placement_ready', 'Placement Ready')], max_length=30),
        ),
    ]
