# Generated by Django 4.2 on 2026-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_aiinterviewsession_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstep',
            name='step_type',
            field=models.CharField(choices=[('profile_created', 'Profile Created'), ('first_code_upload', 'First Code Upload'), ('skills_extracted', 'Skills Extracted'), ('ai_interview_completed', 'AI Interview Completed'), ('skill_verification', 'Skill Verification'), ('document_verification', 'Document Verification'), ('skill_passport_ready', 'Skill Passport Ready')], max_length=30, unique=True),
        ),
    ]
