# Generated by Django 4.2 on 2026-01-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_repofilesnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='repofilesnapshot',
            new_name='skills_repo_repo_ur_35b32f_idx',
            old_name='skills_repor_repo_ur_7c38d7_idx',
        ),
        migrations.RenameIndex(
            model_name='repofilesnapshot',
            new_name='skills_repo_sha_b56614_idx',
            old_name='skills_repor_sha_0e48c8_idx',
        ),
    ]
